modLoader="javafml"
loaderVersion="[40,)"
license="GNU GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues"

[[mods]]
modId="antiqueatlas"
version="${version}"
logoFile="antiqueatlas_icon.png"
displayName="Antique Atlas"
displayURL="https://www.curseforge.com/minecraft/mc-mods/antique-atlas"
credits="Hunternif, Kenkron, osipxd, thecodewarrior, TehNut, crafteverywhere, coolAlias, Ruukas97, Mazdallier, chesterccj305, asiekierka, sam-kirby, esotericist, dadodollabela, Yulife, Waterrail, The-Fireplace, TBM13, Rikshy, GirafiStudios, DrCopernicus, DBotThePony, AugiteSoul, Stereowalker"
authors="Hunternif, tyra314, sisby-folk, kallmetony"
description='''
Antique Atlas is a book that acts like a map featuring infinite scrolling, zoom and custom labeled markers. The map is generated around the player by calculating the average biome in each 16x16 chunk.
'''

[[dependencies.antiqueatlas]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.antiqueatlas]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.antiqueatlas]]
modId="cloth_config"
mandatory=true
versionRange="[8.2.88,)"
ordering="NONE"
side="BOTH"

[[dependencies.antiqueatlas]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "AFTER"
side = "BOTH"
